File uploading and retrieval from ipfs
adityanithariya/Judicature pull request #4
Opened 2023-10-16 19:47 UTC by aditya142003

2023-10-17 13:03 UTC, adityanithariya requested changes

2023-10-17 13:03 UTC, adityanithariya commented on server/.gitignore
> +uploads/*.pdf
Remove this and add `temp` folder to global .gitignore

2023-10-17 13:03 UTC, adityanithariya commented on server/controllers/fileController.js
> +    const filePath = path.join(__dirname, '../', 'temp', filename);
Add a check of `temp` folder exists, before joining path
Create `temp`, if `temp` doesn't exists

2023-10-17 13:03 UTC, adityanithariya commented on server/controllers/fileController.js
> +            message: 'Error in IPFS',
message: `Error in uploading file to IPFS`

2023-10-17 13:03 UTC, adityanithariya commented on server/controllers/fileController.js
> +    let fileData = {
Use of `const` everywhere in this function, would be preferrable

2023-10-17 13:03 UTC, adityanithariya commented on server/controllers/fileController.js
> +            'http://127.0.0.1:5001/api/v0/add/',
Get the url of IPFS from `config.env`, instead of hardcoding it

2023-10-17 13:03 UTC, adityanithariya commented on server/resolvers/Mutation.js
> +                    code: codeMap[response.statusCode]
`message` coming from controller should have first priority, as `codeMap` contains generic messages, debugging on frontend would be easy

2023-10-17 16:44 UTC, aditya142003 commented on server/controllers/fileController.js
> +    let fileData = {
We are assigning new values to the variables.

2023-10-17 18:24 UTC, adityanithariya approved these changes

2023-10-18 05:16 UTC, adityanithariya commented
Raise new PR, unable to merge this one

2023-10-18 05:16 UTC, closed without merging